import doctor from './assets/doktor.jpg';

export const specialists = [
	{
		id: 1,
		name: 'Adam Nowak',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Ząbki',
		image: doctor,
	},
	{
		id: 2,
		name: 'Tomasz Kowalski',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Ząbki',
		image: doctor,
	},
	{
		id: 3,
		name: 'Anna Szymańska',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 4,
		name: 'Karolina Wójcik',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 5,
		name: 'Ewa Kaczmarek',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 6,
		name: 'Robert Nowicki',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 7,
		name: 'Katarzyna Krawczyk',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 8,
		name: 'Marek Jasiński',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 9,
		name: 'Joanna Kowalczyk',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 10,
		name: 'Łukasz Szymczak',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 11,
		name: 'Magdalena Nowakowska',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 12,
		name: 'Marta Kubiak',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 13,
		name: 'Michał Kowalewski',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 14,
		name: 'Aleksandra Woźniak',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
	{
		id: 15,
		name: 'Janusz Pawłowski',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
	{
		id: 16,
		name: 'Monika Lisowska',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
];
