import doctor from './assets/doktor.jpg';

export const specialists = [
	{
		id: 1,
		name: 'Pioter  Gruszkaaaa',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 2,
		name: 'Pioter Pietruszewski',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 3,
		name: 'Pioter Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 4,
		name: 'Pioter Arbuz',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 5,
		name: 'Pioter Marchewka',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia C',
		image: doctor,
	},
	{
		id: 6,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 7,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia C',
		image: doctor,
	},
	{
		id: 8,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 9,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia C',
		image: doctor,
	},
	{
		id: 10,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 11,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia C',
		image: doctor,
	},
	{
		id: 12,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 13,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 14,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 15,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 16,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 17,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
	{
		id: 15,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Przychodnia A',
		image: doctor,
	},
];
