import doctor from './assets/doktor.jpg';

export const specialists = [
	{
		id: 1,
		name: 'Pioter  Gruszkaa',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Ząbki',
		image: doctor,
	},
	{
		id: 2,
		name: 'Pioter Pietruszewski',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Ząbki',
		image: doctor,
	},
	{
		id: 3,
		name: 'Pioter Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 4,
		name: 'Pioter Arbuz',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 5,
		name: 'Pioter Marchewka',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 6,
		name: 'Rysiek Pietruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Przychodnia B',
		image: doctor,
	},
	{
		id: 7,
		name: 'Wacław Chrząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Sulejówek',
		image: doctor,
	},
	{
		id: 8,
		name: 'Rysiek Pietruszska',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 9,
		name: 'Wacław Chrząkałwa',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 10,
		name: 'Rysiek Pietrusszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 11,
		name: 'Wacław Chrzaąkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 12,
		name: 'Wacław Charząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 13,
		name: 'Rysiek Pietaeruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa',
		image: doctor,
	},
	{
		id: 14,
		name: 'Wacław Cherząkała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
	{
		id: 15,
		name: 'Rysiek Pieeetruszka',
		title: 'fizjoterapeuta',
		speciality: 'osteopatia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
	{
		id: 16,
		name: 'Wacław Chrząeekała',
		title: 'fizjoterapeuta',
		speciality: 'fizjoterapia',
		facilities: 'Warszawa-Wesoła',
		image: doctor,
	},
];
